[[collection]]
type = "art_simple"
title = "Black Swan"
subtitle = "2010"
link = "https://www.themoviedb.org/movie/44214-black-swan" # optional
img = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/viWheBd44bouiLCHgNMvahLThqx.jpg"
