[[collection]]
type = "art_simple"
title = "Crime & Punishment"
subtitle = "Fyodor Dostoevsky"
link = "https://www.goodreads.com/book/show/7144"
img = "https://m.media-amazon.com/images/I/612KmKeEYEL._SL1500_.jpg"

