[[collection]]
type = "art_simple"
title = "The Alchemist"
subtitle = "Paulo Coelho"
link = "https://www.goodreads.com/book/show/18144590" # optional
img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FS%2Fcompressed.photo.goodreads.com%2Fbooks%2F1654371463i%2F18144590.jpg&f=1&nofb=1&ipt=11dc4e588f24ad23eeec2da9f45f2b45d7f3b6585dd858a84ce59b413d9f0f13"
