[[collection]]
type = "art_simple"
title = "1984"
subtitle = "George Orwell"
link = "https://www.goodreads.com/book/show/61439040" # optional
img = "https://www.penguin.co.uk/_next/image?url=https%3A%2F%2Fcdn.penguin.co.uk%2Fdam-assets%2Fbooks%2F9780141036144%2F9780141036144-jacket-large.jpg&w=379&q=100"
