[[collection]]
type = "art_simple"
title = "La Haine"
subtitle = "1995"
link = "https://www.themoviedb.org/movie/406-la-haine"
img = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iH8saz6s0Z8SPPrKaMI2KrRzTED.jpg"

[[collection]]
type = "art_simple"
title = "Jojo Rabbit"
subtitle = "2019"
link = "https://www.themoviedb.org/movie/406-la-haine"
img = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7GsM4mtM0worCtIVeiQt28HieeN.jpg"
