[[collection]]
type = "card"
# icon = "/assets/icon-deepseek.svg"
title = "Accurate IC"
link = "https://accurateic.in/"
subtitle = "FullStack Software Engineer, AI Dept"
date = "Aug 2024 -- Present"
content = """
Worked as a full-stack engineer on projects made for clients such as the Indian Navy, Indian Oil Corp, German Police.

For the Indian Navy, developed a web application for an in-house
developed intelligence technology named ISACA
(Intelligent Situational Collision Avoidance).
This application functioned without the need of internet
and internal communication was done through
radio based intranet. I worked on developing the core
functionality for the frontend & backend systems
as well as designing and developing the database.

For the German Police, developed an ML-powered GenSet analytics
and Failure Prediction System codenamed NeuroGen. This is a particularly
backend & database heavy application. I built the whole application
basically from scratch. All the

*Technologies:
[React](https://react.dev/),
[AdonisJS](https://adonisjs.com/),
[JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript),
[TypeScript](https://www.typescriptlang.org/),
[PostgreSQL](https://www.postgresql.org/),
[Tanstack Query]( https://tanstack.com/query/latest ),
[Lucid ORM](https://lucid.adonisjs.com/docs/introduction)*
"""


[[collection]]
type = "card"
# icon = "/assets/icon-deepseek.svg"
title = "MasterSoft"
link = "https://www.mastersofterp.com/"
subtitle = "Software Engineer, R&D Dept"
date = "Aug 2023 - Jun 2024"
content = """
Worked as a Software Engineer as part of an exclusive R&D Team that worked on building innovative projects 
"""


