[[collection]]
type = "art_simple"
title = "Normal People"
subtitle = "2020"
link = "https://letterboxd.com/film/normal-people-2020/"
img = "https://a.ltrbxd.com/resized/film-poster/6/2/0/7/8/1/620781-normal-people-0-1000-0-1500-crop.jpg?v=9a7cce9f55"

[[collection]]
type = "art_simple"
title = "The Pianist"
subtitle = "2002"
link = "https://letterboxd.com/film/the-pianist/"
img = "https://a.ltrbxd.com/resized/film-poster/5/1/6/7/2/51672-the-pianist-0-1000-0-1500-crop.jpg?v=3eee5ac018"